In [1]:
import pandas as pd
import numpy as np
from django_pandas.io import read_frame

dados = Inscricao.objects.all()
total = Inscricao.objects.total_pago()
df = read_frame(dados, fieldnames=['data', 
                                   'atleta', 
                                   'atleta__faixa', 
                                   'atleta__academia', 
                                   'atleta__sexo',
                                   'categoria_peso', 
                                   'valor', 
                                   'valor_absoluto', 
                                   'categoria_idade'])
df['valor_total'] = df.apply(lambda x : x['valor'] + x['valor_absoluto'], axis=1)
df['qtd'] = df.apply(lambda x : 1, axis=1)

In [2]:
pv = df.pivot_table(index=['atleta__academia', 'atleta__sexo'], 
                    columns=['categoria_peso'], 
                    values=['valor_total'], 
                    aggfunc=np.sum, 
                    fill_value=0,
                    margins=True,
                   )
pv

                                  valor_total                              \
categoria_peso                           Galo    Leve Meio Pesado   Médio
atleta__academia     atleta__sexo
Atrittus Jiu Jitsu   Feminino           20.00   20.00           0   20.00
                     Masculino              0   20.00       50.00       0
Bushido              Feminino               0  150.00       50.00       0
                     Masculino         140.00  100.00      110.00  230.00
Evolução Jiu Jitsu   Masculino              0       0       50.00       0
Gracie Barra Cáceres Masculino              0   50.00       50.00       0
LS Team              Masculino          50.00  100.00           0  120.00
Mão Jiu Jitsu        Masculino              0       0           0       0
NS Brotherhood       Feminino               0   50.00           0  100.00
                     Masculino          70.00  190.00      150.00   70.00
Team Ferraz          Masculino              0   50.00           0   70.00
All                                    280.00  730.00      460.00  610.00

                                                                       \
categoria_peso                       Pena  Pesado Pesadíssimo   Pluma
atleta__academia     atleta__sexo
Atrittus Jiu Jitsu   Feminino       50.00       0           0   50.00
                     Masculino     120.00   50.00           0   20.00
Bushido              Feminino       20.00   50.00       20.00   20.00
                     Masculino     110.00   90.00      160.00   80.00
Evolução Jiu Jitsu   Masculino      50.00       0           0       0
Gracie Barra Cáceres Masculino      50.00       0           0       0
LS Team              Masculino          0   50.00      120.00       0
Mão Jiu Jitsu        Masculino          0   50.00           0       0
NS Brotherhood       Feminino           0       0           0       0
                     Masculino      70.00   50.00       50.00  120.00
Team Ferraz          Masculino          0       0       50.00       0
All                                470.00  340.00      400.00  290.00


categoria_peso                    Super Pesado      All
atleta__academia     atleta__sexo
Atrittus Jiu Jitsu   Feminino                0   160.00
                     Masculino           20.00   280.00
Bushido              Feminino                0   310.00
                     Masculino          120.00  1140.00
Evolução Jiu Jitsu   Masculino               0   100.00
Gracie Barra Cáceres Masculino           50.00   200.00
LS Team              Masculino           70.00   510.00
Mão Jiu Jitsu        Masculino               0    50.00
NS Brotherhood       Feminino                0   150.00
                     Masculino           50.00   820.00
Team Ferraz          Masculino           70.00   240.00
All                                     380.00  3960.00

In [3]:
pvt = df.pivot_table(index=['atleta__academia'], columns=['atleta__sexo'], values=['qtd'], aggfunc=np.sum, fill_value=0, margins=True)
pvt

                          qtd
atleta__sexo         Feminino Masculino    All
atleta__academia
Atrittus Jiu Jitsu        5.0       8.0   13.0
Bushido                   8.0      36.0   44.0
Evolução Jiu Jitsu        0.0       2.0    2.0
Gracie Barra Cáceres      0.0       4.0    4.0
LS Team                   0.0      10.0   10.0
Mão Jiu Jitsu             0.0       1.0    1.0
NS Brotherhood            3.0      20.0   23.0
Team Ferraz               0.0       5.0    5.0
All                      16.0      86.0  102.0