In [19]:
import pandas as pd
import numpy as np
from django_pandas.io import read_frame

a = Atleta.objects.all().exclude(id__in=Inscricao.objects.values_list('atleta', flat=True))
df = read_frame(a)
df

,id,nome,sexo,idade,peso,faixa,academia
0,45,Tico Boy,Masculino,12,0.00,Branca,BUSHIDO
1,47,SILVIO HENRIQUE GALEANO,Masculino,15,0.00,Amarela,BUSHIDO
2,49,LUIZ FERNANDO FERREIRA DE ALMEIRA,Masculino,9,0.00,Cinza,CROSS FIGHT
3,50,IAGO SOARES MAGALHAES,Masculino,6,0.00,Cinza,CROSS FIGHT
4,51,MATEUS HENRIQUE DA SILVA PAULINO,Masculino,6,0.00,Cinza,CROSS FIGHT
5,52,DAVI NAUAN HOINASKI,Masculino,9,0.00,Cinza,CROSS FIGHT
6,53,MARIA EDUARDA CAMPOS MOREIRA,Feminino,9,0.00,Cinza,CROSS FIGHT
7,54,ANA ANTONIA SILVA GARCIA MARTINS,Feminino,9,0.00,Cinza,CROSS FIGHT
8,112,LUCAS VIANA,Masculino,15,0.00,Laranja,NS BROTHERHOOD
9,113,MATHEUS BARROSO,Masculino,15,0.00,Amarela,NS BROTHERHOOD
10,114,HEITOR SANTANA,Masculino,9,0.00,Cinza,NS BROTHERHOOD
11,115,LUCAS SANTANA,Masculino,12,0.00,Cinza,NS BROTHERHOOD
12,116,IKARUS BARROS DUARTE,Masculino,9,0.00,Cinza,NS BROTHERHOOD
13,117,PEDRO OTAVIO,Masculino,9,0.00,Cinza,NS BROTHERHOOD
14,124,LUAS O CAETANO COSTA,Masculino,12,0.00,Branca,TEAM FERRAZ
15,131,PEDRO PAULO ATRITUS,Masculino,12,0.00,Amarela,ATRITTUS JJ
16,132,MARIO ATRITUS,Masculino,15,0.00,Cinza,ATRITTUS JJ
17,133,RAFAEL ATRITUS,Masculino,15,0.00,Laranja,ATRITTUS JJ
18,134,LEONARDIO ATRITUS,Masculino,12,0.00,Laranja,ATRITTUS JJ
19,142,EDUARDO KAUE,Masculino,6,0.00,Branca,LS TEAM
20,150,ALEXANDRE NOGUEIRA,Masculino,29,0.00,Branca,ATRITTUS JJ
21,157,DIEGO CORAL,Masculino,15,0.00,Laranja,ATRITTUS JJ
22,159,JOAO GABRIEL,Masculino,9,0.00,Cinza,ATRITTUS JJ
23,161,LUIZ GUSTAVO,Masculino,9,0.00,Branca,ATRITTUS JJ
24,182,SABRINA SAYURI,Feminino,15,0.00,Branca,LS TEAM
25,185,ALANA OLIVEIRA SOLEDADE,Feminino,0,48.00,Branca,LS TEAM
26,187,CLAUDIO GILBERTO DEODATO,Masculino,0,94.30,Branca,ATRITTUS JJ
27,188,ICARO ANDREY BENICIOS REIS,Masculino,0,0.00,Amarela,ATRITTUS JJ
28,189,ADALTO ATRITUS,Masculino,0,0.00,Branca,ATRITTUS JJ